services:
  # DATABASES
  mongodb:
    build:  # If the build file name is different, Mention the file name like this
      context: ./mongodb
      dockerfile: Dockerfile
    image: bsainitin/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
  mysql:
    build: ./mysql
    image: bsainitin/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  # BACKEND
  catalogue:
    build: ./catalogue
    image: bsainitin/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: ./user
    image: bsainitin/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    build: ./cart
    image: bsainitin/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  shipping:
    build: ./shipping
    image: bsainitin/shipping:v1
    container_name: shipping
    depends_on:
      - cart
      - mysql
  payment:
    build: ./payment
    image: bsainitin/payment:v1
    container_name: payment
    depends_on:
      - user
      - cart
      - rabbitmq
  # FRONTEND
  frontend:
    build: ./frontend
    image: bsainitin/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
networks:
  default:
    driver: bridge
    name: roboshop
    external: false # True if user created network manually using docker network command
# VOLUMES
volumes:
  mongodb: # docker volume create mongodb
  redis:
  mysql:
  rabbitmq: